services:
    api:
        image: somestoreapi:latest
        ports:
            - 8081:8081
            - 8080:8080
        restart: unless-stopped
        volumes:
            - ./products.db:/app/products.db